name: WorldProtector
author: Jack Noordhuis
version: 1.1.0
description: Protects worlds from certain events through permissions
main: jacknoordhuis\worldprotect\Main
api:
    - 1.0.0
    - 2.0.0

permissions:
    worldprotector:
        description: WorldProtector's main permission
        default: op

        worldprotector.block:
            description: WorldProtector's main permission for blocky things
            default: op

            worldprotector.block.break:
                description: WorldProtector's permission for block breaking things
                default: op
            worldprotector.block.place:
                description: WorldProtector's permission for block placing things
                default: op
            worldprotector.block.interact:
                description: WorldProtector's permission for block interaction things
                default: op

        worldprotector.player:
            description: WorldProtector's main permission for player things
            default: op

            worldprotector.player.attack:
                description: WorldProtector's permission for player attack things
                default: op
            worldprotector.player.damage:
                description: WorldProtector's permission for player damage things
                default: op
