name: SimpleTest
author: JackNoordhuis
version: 1.0.0
description: Simple plugin that relays certain event realted things to the player, designed for testing purposes.
main: jacknoordhuis\simpletest\Main
api: [1.13.0]