name: Homes
description: Allows each player that joins your server to set a home that they can teleport to!
main: jacknoordhuis\homes\Main
version: 0.0.2
api: [3.0.0]
authors:
  - "JackNoordhuis"

commands:
  home:
    description: "Teleport to your home"
    usage: "/home"
  sethome:
    description: "Set your home to your current position"
    usage: "/sethome"