name: PositionTeller
author: Jack Noordhuis
version: 1.1
description: Sends a constant popup with a players position when activated.
main: jacknoordhuis\positionteller\Main
api: [1.12.0]

commands:
    togglepos:
        description: "Toggles your PositionTeller"
        
permissions:
    positionteller.command:
        description: "Main PositionTeller permission node"
        default: op
    positionteller.command.togglepos.self:
        description: "TogglePos command permission node"
        default: op